#! /bin/sh

URL="http://localhost:8080"

curl -v -H "Accept: application/json" -d name=twittersearchObama -d definition="twittersearch+--query='%23obama'+%7C+file" $URL/streams
curl -v -H "Accept: application/json" -d name=twittersearchBieber -d definition="twittersearch+--query='%23romney'+%7C+file" $URL/streams
curl -v -H "Accept: application/json" -d name=twittersearchRomney -d definition="twittersearch+--query='%23bieber'+%7C+file" $URL/streams

curl -v -H "Accept: application/json" -d name=obamaCount -d definition="tap+twittersearchObama+%7C+aggregatecounter+--fieldName=entities.hashTags.text+--counterName=obamaAggregatedCounter"  "$URL/taps"
curl -v -H "Accept: application/json" -d name=bieberCount -d definition="tap+twittersearchBieber+%7C+aggregatecounter+--fieldName=entities.hashTags.text+--counterName=bieberAggregatedCounter"  "$URL/taps"
curl -v -H "Accept: application/json" -d name=romneyCount -d definition="tap+twittersearchRomney+%7C+aggregatecounter+--fieldName=entities.hashTags.text+--counterName=romneyAggregatedCounter"  "$URL/taps"

